// Downloads the self-hosted webfonts (variable woff2) from Google Fonts and
// rewrites the @font-face CSS to point at local files. Self-hosting keeps the
// site GDPR-clean (no runtime request to Google) — important for an EU business.
// Run: npm run fonts
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = `${ROOT}/public/fonts`;
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  { key: "bricolage", q: "Bricolage+Grotesque:opsz,wght@12..96,200..800" },
  { key: "hanken", q: "Hanken+Grotesk:wght@300..800" },
  { key: "spline", q: "Spline+Sans+Mono:wght@400..600" },
];

// Only keep the subsets we actually need: Latin + Latin-Extended (Lithuanian).
const KEEP = new Set(["latin", "latin-ext"]);

await mkdir(OUT, { recursive: true });
let combined = "/* Self-hosted webfonts — generated by scripts/fetch-fonts.mjs */\n";

for (const { key, q } of FAMILIES) {
  const css = await (
    await fetch(`https://fonts.googleapis.com/css2?family=${q}&display=swap`, {
      headers: { "User-Agent": UA },
    })
  ).text();

  // Split into @font-face blocks, each preceded by a /* subset */ comment.
  const blocks = css.split("/*").slice(1);
  let idx = 0;
  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf("*/")).trim();
    if (!KEEP.has(subset)) continue;
    const block = "/*" + raw;
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    const file = `${key}-${subset}-${idx++}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    await writeFile(`${OUT}/${file}`, buf);
    combined += block.replace(/url\(https:[^)]+\.woff2\)/, `url(./${file})`).trimEnd() + "\n";
    console.log(`  ${file}  (${(buf.length / 1024).toFixed(1)} kB)`);
  }
}

await writeFile(`${OUT}/fonts.css`, combined);
console.log("Wrote public/fonts/fonts.css");
