// Reads the *.raw.css fetched via curl, downloads the woff2 (via curl, to respect
// the environment's proxy CA), and writes a localized public/fonts/fonts.css.
import { readFile, writeFile, readdir } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = `${dirname(dirname(fileURLToPath(import.meta.url)))}/public/fonts`;
const KEEP = new Set(["latin", "latin-ext"]); // Lithuanian needs latin-ext
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

let combined = "/* Self-hosted webfonts — generated by scripts/localize-fonts.mjs */\n";
const raws = (await readdir(OUT)).filter((f) => f.endsWith(".raw.css")).sort();

for (const raw of raws) {
  const key = raw.replace(".raw.css", "");
  const css = await readFile(`${OUT}/${raw}`, "utf8");
  const blocks = css.split("/*").slice(1);
  let idx = 0;
  for (const chunk of blocks) {
    const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
    if (!KEEP.has(subset)) continue;
    const block = "/*" + chunk;
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    const file = `${key}-${subset}-${idx++}.woff2`;
    execFileSync("curl", ["-s", "-A", UA, url, "-o", `${OUT}/${file}`]);
    combined += block.replace(/url\(https:[^)]+\.woff2\)/, `url(./${file})`).trimEnd() + "\n";
    console.log(`  ${file}`);
  }
}

await writeFile(`${OUT}/fonts.css`, combined);
console.log("Wrote public/fonts/fonts.css");
